apiVersion: apps/v1
kind: Deployment
metadata:
  name: umap-deployment
  labels:
    app: umap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umap
  template:
    metadata:
      labels:
        app: umap
    spec:
      containers:
      - name: umap # v1.0.0
        image: slithiaote/umap-api@sha256:de2e91f344369af65402645d4a1f39a16b24802510abb375d59844ba178fe292
        ports:
        - containerPort: 8000
        env:
        - name: APP_ENV
          value: "prod_user"
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: tracking-uri
        - name: MLFLOW_TRACKING_USERNAME
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: username
        - name: MLFLOW_TRACKING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-secrets
              key: password