apiVersion: apps/v1
kind: Deployment
metadata:
  name: umap-deployment
  labels:
    app: umap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umap
  template:
    metadata:
      labels:
        app: umap
    spec:
      containers:
      - name: umap
        image: slithiaote/umap-api:v0.2.0
        ports:
        - containerPort: 8000