apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit # v1.0.0
        image: slithiaote/umap-streamlit@sha256:bac2edf3d908b51f2ff2b6fced2728615dbbf6a1002ef6bf210674ae5747e377
        ports:
        - containerPort: 8501