apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit # v0.5.1
        image: slithiaote/umap-streamlit@sha256:f695ac5db246c0c3d577dba02e5dc198b34456cdca1506d483a407624e78a360
        ports:
        - containerPort: 8501